# ============================================================================ #
# Proximity devphp framework config
# ============================================================================ #
# admin:
#   login: 
#   password: 

# ============================================================================ #
# Database settings
# ============================================================================ #
# db:
#   adapter: pdo_mysql
#   host: localhost
#   dbname: database
#   username: user_name
#   password: password
# 
# db_STAGING:
#   adapter: pdo_mysql
#   host: localhost
#   dbname: database
#   username: user_name
#   password: password
# 
# db_PRODUCTION:
#   adapter: pdo_mysql
#   host: localhost
#   dbname: database
#   username: user_name
#   password: password

# ============================================================================ #
# Multilang options
# ============================================================================ #
multilang:
  default: nl-BE
  # dir: assets/locales/ # from root, default is assets/locales/

# ============================================================================ #
# ERROR SETTINGS
# ============================================================================ #
errors:
  # custom_page: error.html.php # must be in the vies dir or subdir
  # custom_layout: false # false = do not use default layout, true = use default layout 

# ============================================================================ #
# TEMPLATE SETTINGS
# ============================================================================ #
# compile_templates: false # true by default

# ============================================================================ #
# TESTING
# ============================================================================ #
verbose: false

# ============================================================================ #
# XPORTER
# ============================================================================ #
# xporter:
#   active: true
#   base_url: 'http://dev.local'
#   base_path: '/home'
